$PWD/xkb/:$XDG_CONFIG_HOME/xkb

$PWD/nvim/:$XDG_CONFIG_HOME/nvim

#$PWD/alacritty/:$XDG_CONFIG_HOME/alacritty
$PWD/foot/:$XDG_CONFIG_HOME/foot

$PWD/tmux/tmux.conf:$XDG_CONFIG_HOME/tmux/tmux.conf

#$PWD/fish/config.fish:$XDG_CONFIG_HOME/fish/config.fish
$PWD/zsh/zshrc:$HOME/.zshrc
$PWD/zsh/custom.zsh-theme:$HOME/.oh-my-zsh/custom/themes/custom.zsh-theme

$PWD/kde/RosePine.colors:$XDG_DATA_HOME/color-schemes/RosePine.colors
$PWD/kde/kdeglobals:$XDG_CONFIG_HOME/kdeglobals

