export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="custom"

plugins=(git zsh-autosuggestions fzf)

source $ZSH/oh-my-zsh.sh

export EDITOR="nvim"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"
export XDG_CACHE_HOME="${HOME}/.cache"

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=243"

bindkey "^H" backward-kill-word

